#! /bin/sh
ln -s /usr/src/madd-games/apoc/scripts scripts
ln -s /usr/src/madd-games/apoc/linux.rule linux.rule

echo ".PHONY: game">Makefile
echo "game:">>Makefile
echo "	@python /usr/src/madd-games/apoc/build.py game --with-sdk $@">>Makefile
