#! /usr/bin/python
# Convert a PNG file into a C++ file with Apocalypse texture data.

from PIL import Image
import sys, os

def compileImage(inFileName, outFileName, imageName):
	img = Image.open(inFileName)
	width, height = img.size

	f = open(outFileName, "wb")
	f.write("// Do not modify this file; it was autoatically generated by scripts/image.py!\n")
	f.write("#include <Apoc/Entity/Texture.h>\n")
	f.write("\n")
	f.write("extern \"C\" const int imgWidth_%s = %d;\n" % (imageName, width))
	f.write("extern \"C\" const int imgHeight_%s = %d;\n" % (imageName, height))
	f.write("extern \"C\" const Texture::Texel imgTexels_%s[] = {\n" % imageName)

	for y in range(0, height):
		for x in range(0, width):
			pixel = img.getpixel((x, height-y-1))
			outPixel = None
			if len(pixel) == 3:
				outPixel = (float(pixel[0])/255.0, float(pixel[1])/255.0, float(pixel[2])/255.0, 1.0)
			else:
				# Assuming RGBA
				outPixel = (float(pixel[0])/255.0, float(pixel[1])/255.0, float(pixel[2])/255.0, float(pixel[3])/255.0)

			f.write("\t{%f, %f, %f, %f},\n" % outPixel)

	f.write("};\n")
	f.close()

	return (width, height)
